# Generated by Django 3.2 on 2022-08-23 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('hackernews_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 8, 23, 18, 22, 51, 804223))),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('post_url', models.CharField(blank=True, default='http://stoplight.io/prism/', max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsID',
            fields=[
                ('hackernews', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 8, 23, 18, 22, 51, 804223))),
            ],
        ),
    ]
