# Generated by Django 3.2 on 2022-08-23 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_auto_20220823_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='post_url',
            field=models.CharField(blank=True, default='http://stoplight.io/prism/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 22, 55, 58, 906552)),
        ),
    ]
