# Generated by Django 3.2 on 2022-08-24 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_alter_newsid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='path',
            field=models.CharField(blank=True, default='user', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newsid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 9, 48, 16, 414382)),
        ),
    ]
