# Generated by Django 3.2 on 2022-08-25 05:24

import apiapp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0012_alter_newsid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=apiapp.models.UCDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='newsid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 5, 24, 7, 893223)),
        ),
    ]
