# Generated by Django 3.2 on 2022-08-25 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0013_auto_20220825_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 7, 17, 29, 421212)),
        ),
    ]
