# Generated by Django 3.2 on 2022-08-25 22:12

import apiapp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0014_alter_newsid_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('author_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('by', models.CharField(blank=True, max_length=200, null=True)),
                ('time', apiapp.models.UCDateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='newsid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 22, 12, 15, 147028)),
        ),
    ]
