# Generated by Django 3.2 on 2022-08-31 10:54

import apiapp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0030_alter_newsid_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.BigIntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('by', models.CharField(default='user', max_length=200)),
                ('time', apiapp.models.UCDateTimeField(default=datetime.datetime.now)),
                ('comment_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='by',
            field=models.CharField(default='user', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 10, 53, 44, 273438)),
        ),
    ]
